language: generic
env:
  HUGO_VERSION: "0.49.2"

install:
  - curl -sSL https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz -o /tmp/hugo.tar.gz
  - tar -xzf /tmp/hugo.tar.gz -C $HOME/bin

script:
  - npm install --prefix themes/code4
  - npm run build --prefix themes/code4
  - hugo --baseURL $BASE_URL

before_deploy:
  - pyenv global system 3.6
  - pip3 install --user awscli

deploy:
  provider: script
  script: aws s3 sync public s3://$S3_BUCKET_NAME --region $S3_BUCKET_REGION --acl public-read --delete
  skip_cleanup: true
  on:
    branch: master
